### ISSUE TITLE
Pick descriptive filename

### ISSUE THREAD

**Issue by aggsol** [aggsol/DashPodder#2]
Given the following feed:

http://www.spreaker.com/user/8809964/episodes/feed

dashpodder grabs the file at:

http://api.spreaker.com/episode/14029678

as opposed to the longer and more descriptive:

http://api.spreaker.com/download/episode/14029678/dust_boot_camp_episode_2_axis_overview_part_1.mp3

**Comment by mattcaron** [comment]
So, I looked at this a little bit before I ran out of time.

It's not the XSLT enclosure parsing - it gets the URL out just fine, for example:

http://api.spreaker.com/download/episode/14015554/skirmish_supremacy_episode_104.mp3

But, then DLURL gets set to:

http://d1dwvcwq657ipv.cloudfront.net/episodes/original/22357605?episode_id=14015554&response-content-disposition=attachment%3Bfilename%3D%22skirmish_supremacy_episode_104.mp3%22&Expires=1519327075&Signature=oQ7nW5kADOeUV7wMraeivvKaiLlajM6vuXQ1SfkkMHugfLcy7ce6hN1h24oQCg1wYqSTHlghEroNfvnIbxJWh8m4GCUepNGGtAE2SCYdr1JuCn6Iogq%7EGBTW6xpz0C8%7Edi%7EOYFeONMb9Bxj4PQdu6Y6OsGufNHf%7EHpMLYbuh8Mc_&Key-Pair-Id=APKAJBD223KRVW6VKWSA

And that gets passed to fix_url.

I'm still thinking of the best way to detect and fix that.

**Comment by aggsol** [comment]
@mattcaron I added a special fix url the scrapes the filename from the cloudfront URL, should work now. Please give it a try and report any other feed that does not work!

**Comment by mattcaron** [comment]
Works great, thank you!
