### ISSUE TITLE
Fails to download podcasts with quotes in them

### ISSUE THREAD

**Issue by mattcaron** [aggsol/DashPodder#2]
Follow on to https://github.com/aggsol/DashPodder/issues/1. The fix still has issues:

```
Checking http://feeds.cato.org/CatoDailyPodcast -- get all episodes.
NEW: Fetching Consumer-Financial-Protection-Bureau-Its-Still-Unaccountable.mp3 and saving in Cato_Daily_Podcast directory.
NEW: Fetching Trump-to-Meet-with-North-Korea__039_s-Kim-Jong-Un.mp3 and saving in Cato_Daily_Podcast directory.
Error: Failed to load https://cdn.cato.org/dailypodcast/Trump-to-Meet-with-North-Korea&.
---
NEW: Fetching Who-Pays-the-Price-When-You-Don__039_t-Get-A-Speedy-Trial-You-Do.mp3 and saving in Cato_Daily_Podcast directory.
Error: Failed to load https://cdn.cato.org/dailypodcast/Who-Pays-the-Price-When-You-Don&.
---
NEW: Fetching This-Year-Big-Content__039_Likely-Won__039_t-Push-for-Extending-Copyright.mp3 and saving in Cato_Daily_Podcast directory.
Error: Failed to load https://cdn.cato.org/dailypodcast/This-Year-Big-Content&.
```

And I have no idea why it messes up the formatting. It also doesn't seem to honor the code formatting tags.

**Comment by aggsol** [comment]
This is weird, I will further investigate. Do you mean the wrong `_039` in the file name? I tend to complete remove quotes from the file names as I use them as IDs. Also there are now `&` in the URL that is also wrong. Thank you for reporting.

**Comment by aggsol** [comment]
I cannot reproduce your issue: Which OS are you using? Also what are the versions of Bash, curl, wget and sed you are using?

**Comment by mattcaron** [comment]
Ubuntu 16.04.4 (soon to upgrade to 18.04)
bash 4.3.48
curl 7.47.0
wget 1.17.1
sed 4.2.2

relevant config line is:

http://feeds.cato.org/CatoDailyPodcast Cato_Daily_Podcast all

Happy to test anything you need me to and if you need shell on the box to use it as a test platform, I can arrange that.

**Comment by mattcaron** [comment]
To answer your earlier question, when I said it has issues, my main concern is that it doesn't actually download the podcast. Removing the quotes in the output file is fine (I'd just flat remove them, so Don't becomes Dont), but it also looks like it's mangling the URL so the URL resolution fails in some fashion.

**Comment by aggsol** [comment]
I am about to upgrade my systems to Ubunut 18.04 myself today.

0. Make a backup of your `$PODLOG` file (default is: `$BASEDIR/podcast.log` ). This files contains all podcast considered as download/already fetched.
1. Remove the entries of the missing/broken pocasts from `$PODLOG` (Just remove all lines that contain a quote).
2. Get current version from Master (Version: v1.1.3-alpha). This version has debug output enabled.
3. Try again with the `--verbose` option and paste the output of the broken podacasts here

**Comment by aggsol** [comment]
@mattcaron I still find it curious where the `039` and `&#039;` come from. Those are HTML entities probably coming from `wget`. Can you please execute the `locale` command on you machine and paste it here?!

**Comment by aggsol** [comment]
Can you also paste me the output of `xsltproc --version`

**Comment by aggsol** [comment]
@mattcaron I pushed a new version to msater. Can you please try the steps from above again?

**Comment by mattcaron** [comment]
And thank you for yours! I am sorry for wasting your time chasing a ghost.

Oh, and I did test with the latest code and it does still work, so it's not like the proposed fixes caused any issues that I could find.
