### ISSUE TITLE
Weird curl error.

### ISSUE THREAD

**Issue by mattcaron** [aggsol/DashPodder#3]
If I try to get this in my subscriptions.conf:
`http://feeds.feedburner.com/DarkerProjectsAliveInside Darker_Projects_Alive_Inside all`

I get messages like these:

`DEBUG: Base URL:
http://feedproxy.google.com/~r/DarkerProjectsAliveInside/~5/fYA3zJilOGk/AliveInside03_StateOfGrace3.mp3
curl: (7) Failed to connect to localhost port 80: Connection refused
DEBUG: Download URL: http://localhost/audio/aliveinside/AliveInside03_StateOfGrace3.mp3
DEBUG: FINAL FILENAME = AliveInside03_StateOfGrace3.mp3
NEW: Fetching AliveInside03_StateOfGrace3.mp3 and saving in Darker_Projects_Alive_Inside directory.
DEBUG: FILESIZE: 0
Error: Failed to load http://localhost/audio/aliveinside/AliveInside03_StateOfGrace3.mp3.`

Maybe it's the ~ in the filename or something?

**Comment by aggsol** [comment]
Are the other episodes like 'AliveInside04_TheBarrier.mp3' and 'AliveInside05_SeasonOfTheDead1.mp3' get downloaded?

The domains 'darkerprojectsproductions.com' and ''darkerprojectsfanworks.com are no longer registered where the older episodes are according to the feed. Newer episodes are hosted on 'darkerprojects.dreamhosters.com' which works. They need to updated their feed.

**Comment by mattcaron** [comment]
No, all of those others fail too.

And yeah, it looks like a dead link.

What confused me was the reference to localhost. I figured it was the URL munging or something. But, indeed, opening it in a browser fails.

Sorry for the trouble.

**Comment by aggsol** [comment]
no problem, as my *only customer* you get first class support ;-)
